### ISSUE TITLE
enclosingCharacter 

### ISSUE THREAD

**Issue by alfioww** [react-csv/react-csv#178] opened 2019-10-09 04:05 UTC
I tried using this new enclosingCharacter prop but it does not seem to work.
I used it like explained in the README, that is with the following code:

`<CSVLink data={csvData} separator=';' filename={csvName} enclosingCharacter={`'`}>`
 ` {/* my button */}`
`</CSVLink>`

In the resulting downloaded CSV file, the enclosing characters are the default ones, that is double-quotes.

I read the files modified in this PR and everything seems OK.
Could someone tell me if I am using it the wrong way?

Thanks in advance 😊

**Comment by hademo** [comment] 2019-10-22 11:50
Encountering the same problem.

**Comment by Tonytonyy** [comment] 2019-11-28 08:07
me too

**Comment by mccabemj** [comment] 2019-12-23 14:57
Duplicate of #191

**Closed by mccabemj** 2019-12-23 14:57 UTC

**Comment by TAGC** [comment] 2021-11-11 11:58
And how are we meant to avoid enclosing characters at all? Why is that even the default? Most CSV files don't enclose the values in quotes because the commas are sufficient to keep them separated.

**Comment by TAGC** [comment] 2021-11-11 12:25
For those that encounter a similar problem, the workaround we've found is to use [this CSV library](https://github.com/dolezel/react-csv-downloader) instead. The alternative library also makes it a lot easier to support the very common use case of fetching data from an API and downloading it as CSV on button click, something [this library doesn't support as well.](https://github.com/react-csv/react-csv/issues/72).

**Comment by yakumomutsuki** [comment] 2022-12-22 05:35
I have confirmed that the following will generate a CSV without quotes. Please try it.

```
enclosingCharacter={""}
```
